name: evaluate
description: Evaluate math expressions.
version: 0.0.1
author: Edson Onildo <inbox.edsononildo@gmail.com>
homepage: https://github.com/edsonbonfim/evaluate

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  test: ^1.15.2